# Generated by Django 3.0.7 on 2020-06-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(upload_to='news'),
        ),
    ]
