# Generated by Django 3.0.7 on 2020-06-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_auto_20200619_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='link',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
